### ISSUE TITLE
Is it supposed to work out of the box?

### ISSUE THREAD

**Issue by j0k3r** [nhoizey/PinboardInGoogle#6]
I mean, without installing jQuery for example?

I've cloned it, drag the `.js` in the extension page and when I perform a search on Google I got an error about `$` undefined.

> Uncaught ReferenceError: $ is not defined

![](https://s3.amazonaws.com/f.cl.ly/items/1o362o0u3j0B0v021k2d/Image%202015-03-04%20at%2010.01.26%20PM.png)

Might be related to #1 :)

**Comment by nhoizey** [comment]
Related to #7, sorry. And #1 also, then.
